import type { Metadata } from "next";
import "./globals.css";
import localFont from "@next/font/local";

const RedHatText = localFont({
  src: [
    {
      path: "../public/assets/fonts/RedHatText/RedHatText-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/assets/fonts/RedHatText/RedHatText-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../public/assets/fonts/RedHatText/RedHatText-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-RedHat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={RedHatText.variable}>{children}</body>
    </html>
  );
}
